---
engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  csslint:
    enabled: false
  scss-lint:
    enabled: false
    checks:
      Shorthand:
        enabled: false
  eslint:
    enabled: false
    extensions:
    - .es6
    - .js
    - .jsx
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrics/ParameterLists:
        enabled: false
      Rubocop/Style/StringLiterals:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  shellcheck:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- config/**/*
- db/**/*
- script/**/*
- spec/**/*
- vendor/**/*
